version: '3.7'

services:
# https://hub.docker.com/_/postgres/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

  app:
    image: spring-hiber-image
    restart: always
    environment:
      DB-URL: spring-hiber_db_1
      DB-USER: example
      DB-PASS: example
    ports:
      - 8080:8080