version: '3.7'

services:
# https://hub.docker.com/_/postgres/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: spring-hiber
    restart: always
    environment:
      DB-USER: example
      DB-PASS: example